# Generated by Django 4.1.5 on 2023-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comm_lease_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Posted', models.TextField(null=True)),
                ('Proptype', models.TextField(null=True)),
                ('Link', models.TextField()),
                ('Retailer', models.TextField()),
                ('BHK', models.TextField()),
                ('Locality', models.TextField()),
                ('City', models.TextField()),
                ('Price', models.TextField()),
                ('Carpet_Area', models.TextField()),
                ('Washroom', models.TextField()),
                ('Facing', models.TextField()),
                ('Pantry', models.TextField()),
                ('Parking', models.TextField()),
                ('Water_Availability', models.TextField()),
                ('Price_Sqft', models.TextField()),
                ('Property_Age', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='comm_sale_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Posted', models.TextField()),
                ('Proptype', models.TextField()),
                ('Link', models.TextField()),
                ('Owner', models.TextField()),
                ('Locality', models.TextField()),
                ('City', models.TextField()),
                ('Price', models.TextField()),
                ('Price_Sqft', models.TextField()),
                ('Washroom', models.TextField()),
                ('Carpet_Area', models.TextField()),
                ('Parking', models.TextField()),
                ('Property_Age', models.TextField()),
                ('Facing', models.TextField()),
                ('Water_Availability', models.TextField()),
                ('Pantry', models.TextField()),
                ('Overlooking', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='res_pg_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Posted_by', models.TextField()),
                ('Proptype', models.TextField()),
                ('Link', models.TextField()),
                ('Owner', models.TextField()),
                ('Locality', models.TextField()),
                ('City', models.TextField()),
                ('Charges', models.TextField()),
                ('PG_for', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='res_rent_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Posted', models.TextField()),
                ('Proptype', models.TextField(null=True)),
                ('Link', models.TextField()),
                ('Owner', models.TextField()),
                ('BHK', models.TextField()),
                ('Locality', models.TextField()),
                ('City', models.TextField()),
                ('Rent', models.TextField()),
                ('Carpet_Area', models.TextField()),
                ('Furnishing', models.TextField()),
                ('Facing', models.TextField()),
                ('Tenant', models.TextField()),
                ('Floor', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='res_sale_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Posted', models.TextField()),
                ('Proptype', models.TextField(null=True)),
                ('Link', models.TextField()),
                ('Owner', models.TextField()),
                ('BHK', models.TextField()),
                ('Locality', models.TextField()),
                ('City', models.TextField()),
                ('Price', models.TextField()),
                ('Carpet_Area', models.TextField()),
                ('Furnishing', models.TextField()),
                ('Bathrooms', models.TextField()),
                ('Facing', models.TextField()),
                ('Status', models.TextField()),
                ('Transaction', models.TextField()),
                ('Price_Sqft', models.TextField()),
                ('Floor', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
