# Generated by Django 4.1.5 on 2023-01-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapinew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comm_sale_model',
            name='Price_Sqft',
        ),
        migrations.RemoveField(
            model_name='comm_sale_model',
            name='Washroom',
        ),
    ]
