# Generated by Django 4.1.5 on 2023-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapinew', '0003_no_broker_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='no_broker_model',
            name='Nearby',
            field=models.TextField(null=True),
        ),
    ]
