# Generated by Django 4.1.5 on 2023-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapinew', '0005_no_broker_sale_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='no_broker_comm_rent_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Posted', models.TextField(null=True)),
                ('Link', models.TextField()),
                ('Rent', models.TextField()),
                ('Deposit', models.TextField()),
                ('Nearby', models.TextField(null=True)),
                ('SQFT', models.TextField()),
                ('Floor', models.TextField()),
                ('Prop_Type', models.TextField()),
                ('Furnishing', models.TextField()),
                ('Availability', models.TextField()),
                ('Parking', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='no_broker_comm_sale_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Posted', models.TextField(null=True)),
                ('Link', models.TextField()),
                ('Rent', models.TextField()),
                ('Deposit', models.TextField()),
                ('Nearby', models.TextField(null=True)),
                ('SQFT', models.TextField()),
                ('Floor', models.TextField()),
                ('Prop_Type', models.TextField()),
                ('Furnishing', models.TextField()),
                ('Availability', models.TextField()),
                ('Parking', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='no_broker_pg_model',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date_Posted', models.TextField(null=True)),
                ('Link', models.TextField()),
                ('Rent', models.TextField()),
                ('Deposit', models.TextField()),
                ('Nearby', models.TextField(null=True)),
                ('Room_Type', models.TextField()),
                ('Preferred_Tenants', models.TextField()),
                ('Food', models.TextField()),
                ('Parking', models.TextField()),
                ('Possesion_By', models.TextField()),
            ],
        ),
    ]
