# Generated by Django 4.1.5 on 2023-02-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapinew', '0006_no_broker_comm_rent_model_no_broker_comm_sale_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='no_broker_comm_sale_model',
            old_name='Availability',
            new_name='Apt_Type',
        ),
        migrations.RenameField(
            model_name='no_broker_comm_sale_model',
            old_name='Deposit',
            new_name='Bathrooms',
        ),
        migrations.RenameField(
            model_name='no_broker_comm_sale_model',
            old_name='Floor',
            new_name='EMI',
        ),
        migrations.RenameField(
            model_name='no_broker_comm_sale_model',
            old_name='Furnishing',
            new_name='Facing',
        ),
        migrations.RenameField(
            model_name='no_broker_comm_sale_model',
            old_name='Prop_Type',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='no_broker_comm_sale_model',
            name='Rent',
        ),
    ]
