# Generated by Django 4.1.5 on 2023-01-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='date',
        ),
        migrations.AlterField(
            model_name='entries',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
