# Generated by Django 4.1.5 on 2023-01-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_entries_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
