# Generated by Django 4.1.5 on 2023-01-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_entries_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='owner',
        ),
        migrations.AddField(
            model_name='entries',
            name='Bathrooms',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Carpet_Area',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Date_Posted',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Description',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Facing',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Floor',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Furnisng',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Link',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Locality',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Price',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Price_Sqft',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Status',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Transaction',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='bHK',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='city',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='entries',
            name='Owner',
            field=models.TextField(default='none'),
        ),
    ]
