# Generated by Django 4.1.5 on 2023-01-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_rename_furnisng_entries_furnishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='Bathrooms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Carpet_Area',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Date_Posted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Facing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Floor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Furnishing',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Locality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Owner',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Price_Sqft',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='Transaction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='bHK',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entries',
            name='city',
            field=models.TextField(),
        ),
    ]
